security:
    encoders:
        App\Entity\Usuario:
            algorithm: bcrypt
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        proveedor:
            entity:
                class: App\Entity\Usuario
                property: correo
        users_in_memory: { memory: null }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            form_login:
                login_path: /iniciar-sesion
                check_path: /autenticar-sesion
                failure_path: /error-sesion
                provider: proveedor
            logout:
                path: /cerrar-sesion
                target: /iniciar-sesion
            lazy: true
            provider: users_in_memory

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/tarea-crear, roles: ROLE_Usuario }
        - { path: ^/tarea, roles: ROLE_Usuario }
        - { path: ^/tarea-editar, roles: ROLE_Usuario }
        - { path: ^/mis-tareas, roles: ROLE_Usuario }
        - { path: ^/tarea-guardar, roles: ROLE_Usuario }
        - { path: ^/tarea-actualizar, roles: ROLE_Usuario }
        - { path: ^/tarea-borrar, roles: ROLE_Usuario }

when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
