<?php

namespace Container9MRZ35i;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QLi5U4nService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qLi5U4n' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qLi5U4n'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'tarea' => ['privates', '.errored..service_locator.qLi5U4n.App\\Entity\\Tarea', NULL, 'Cannot autowire service ".service_locator.qLi5U4n": it references class "App\\Entity\\Tarea" but no such service exists.'],
            'usuario' => ['privates', '.errored..service_locator.qLi5U4n.Symfony\\Component\\Security\\Core\\User\\UserInterface', NULL, 'Cannot autowire service ".service_locator.qLi5U4n": it references interface "Symfony\\Component\\Security\\Core\\User\\UserInterface" but no such service exists. Did you create a class that implements this interface?'],
        ], [
            'tarea' => 'App\\Entity\\Tarea',
            'usuario' => 'Symfony\\Component\\Security\\Core\\User\\UserInterface',
        ]);
    }
}
