<?php

namespace Container9MRZ35i;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Vks9FhFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Vks9FhF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Vks9FhF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'tarea' => ['privates', '.errored..service_locator.Vks9FhF.App\\Entity\\Tarea', NULL, 'Cannot autowire service ".service_locator.Vks9FhF": it references class "App\\Entity\\Tarea" but no such service exists.'],
        ], [
            'tarea' => 'App\\Entity\\Tarea',
        ]);
    }
}
