<?php

namespace Container9MRZ35i;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTareaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Vks9FhF.App\Entity\Tarea' shared service.
     *
     * @return \App\Entity\Tarea
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Vks9FhF": it references class "App\\Entity\\Tarea" but no such service exists.');
    }
}
