<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHJTVJMa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHJTVJMa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHJTVJMa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHJTVJMa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHJTVJMa\App_KernelDevDebugContainer([
    'container.build_hash' => 'HJTVJMa',
    'container.build_id' => 'e6c9d65c',
    'container.build_time' => 1674834513,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHJTVJMa');
